name: twitter
description: Twitter app Created by Ãnh.

version: 1.0.7+12

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  get_it: ^7.7.0

  freezed_annotation: ^2.4.1
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  firebase_auth: ^4.19.5
  firebase_database: ^10.5.5
  firebase_analytics: ^10.10.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  equatable: ^2.0.5
  image_picker: ^1.1.1
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  firebase_messaging: ^14.9.2
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  google_fonts: ^6.2.1
  firebase_remote_config: ^4.4.5
  firebase_dynamic_links: ^5.5.5
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  translator: ^1.0.0
  flutter_iconly: ^1.0.2

dev_dependencies:
  test: ^1.17.10
  flutter_test:
    sdk: flutter
  # freezed: ^0.12.6
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon-400.png"
  image_path_android: "assets/images/icon-400.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon-48.png
    - assets/images/icon-480.png
    - assets/images/icon-400.png
    - assets/images/qr.png
    - assets/images/bulb.png
    - assets/images/google_logo.png
    - assets/images/error_image.png

  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic


